import { jsPDF } from 'jspdf'

function formatDate(date) {
  const d = String(date.getDate()).padStart(2, '0')
  const m = String(date.getMonth() + 1).padStart(2, '0')
  const y = date.getFullYear()
  return `${d}/${m}/${y}`
}

function pdfFileName(sourceFileName) {
  const lastDot = sourceFileName.lastIndexOf('.')
  const base = lastDot !== -1 ? sourceFileName.slice(0, lastDot) : sourceFileName
  return `${base}-analysis-report.pdf`
}

function addFooter(doc) {
  const pageCount = doc.internal.getNumberOfPages()
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i)
    doc.setFontSize(9)
    doc.setTextColor('#9CA3AF')
    doc.text('Generated by Data Analyzer Tool', 105, 290, { align: 'center' })
  }
}

export default function exportReport(analysisResult, qualityReport, fileName) {
  const doc = new jsPDF({ unit: 'mm', format: 'a4' })
  let y = 20

  function checkPageBreak(needed = 20) {
    if (y + needed > 260) {
      doc.addPage()
      y = 20
    }
  }

  function sectionHeading(text) {
    checkPageBreak(16)
    doc.setFontSize(14)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor('#111827')
    doc.text(text, 20, y)
    y += 8
  }

  // ── Header ──────────────────────────────────────────────────────────────
  doc.setFontSize(20)
  doc.setFont('helvetica', 'bold')
  doc.setTextColor('#111827')
  doc.text('Data Analysis Report', 20, y)

  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor('#6B7280')
  doc.text(`Source file: ${fileName}`, 20, y + 10)

  doc.setFontSize(10)
  doc.text(`Generated on: ${formatDate(new Date())}`, 20, y + 18)

  doc.setDrawColor('#D1D5DB')
  doc.line(20, y + 24, 190, y + 24)
  y += 35

  // ── Summary ─────────────────────────────────────────────────────────────
  sectionHeading('Summary')
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor('#374151')
  const summaryLines = doc.splitTextToSize(analysisResult.summary, 170)
  for (const line of summaryLines) {
    checkPageBreak(7)
    doc.text(line, 20, y)
    y += 7
  }
  y += 10

  // ── Key Insights ─────────────────────────────────────────────────────────
  sectionHeading('Key Insights')
  for (const insight of analysisResult.keyInsights) {
    checkPageBreak(20)
    doc.setFontSize(12)
    doc.setFont('helvetica', 'bold')
    doc.setTextColor('#111827')
    doc.text(insight.title, 20, y)
    y += 7

    doc.setFontSize(11)
    doc.setFont('helvetica', 'normal')
    doc.setTextColor('#374151')
    const lines = doc.splitTextToSize(insight.description, 160)
    for (const line of lines) {
      checkPageBreak(7)
      doc.text(line, 20, y)
      y += 7
    }
    y += 8
  }

  // ── Recommendations ──────────────────────────────────────────────────────
  sectionHeading('Recommendations')
  analysisResult.recommendations.forEach((rec, i) => {
    const lines = doc.splitTextToSize(`${i + 1}. ${rec}`, 170)
    for (const line of lines) {
      checkPageBreak(7)
      doc.setFontSize(11)
      doc.setFont('helvetica', 'normal')
      doc.setTextColor('#374151')
      doc.text(line, 20, y)
      y += 7
    }
    y += 6
  })

  // ── Data Quality ─────────────────────────────────────────────────────────
  sectionHeading('Data Quality')
  checkPageBreak(10)
  doc.setFontSize(11)
  doc.setFont('helvetica', 'normal')
  doc.setTextColor('#374151')
  doc.text(`Quality Score: ${qualityReport.qualityScore}/100`, 20, y)
  y += 8

  for (const warning of qualityReport.warnings) {
    checkPageBreak(7)
    doc.setFontSize(10)
    doc.setTextColor('#6B7280')
    const lines = doc.splitTextToSize(`• ${warning}`, 170)
    for (const line of lines) {
      checkPageBreak(7)
      doc.text(line, 20, y)
      y += 7
    }
  }

  // ── Footer on all pages ──────────────────────────────────────────────────
  addFooter(doc)

  doc.save(pdfFileName(fileName))
}
